# Generated by Django 3.0.3 on 2022-05-13 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('lastUpdatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('region_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(max_length=12)),
                ('area_by_m2', models.CharField(max_length=10)),
                ('width_of_facade', models.IntegerField()),
                ('width_of_road', models.IntegerField()),
                ('direction', models.CharField(choices=[('North', 'North'), ('East', 'East'), ('South', 'South'), ('West', 'West')], max_length=15, unique=True)),
                ('is_legal', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_posts', to='api.Member')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_posts', to='api.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Member')),
                ('realEstatePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.RealEstatePost')),
            ],
        ),
    ]
