# Generated by Django 3.0.3 on 2022-05-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatepost',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
