# Generated by Django 3.0.3 on 2022-05-14 11:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_realestatepost_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatepost',
            name='image_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to),
        ),
    ]
