# Generated by Django 3.0.3 on 2022-05-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220515_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatepost',
            name='direction',
            field=models.CharField(choices=[('North', 'North'), ('East', 'East'), ('South', 'South'), ('West', 'West')], max_length=15),
        ),
    ]
