# Generated by Django 3.0.3 on 2022-05-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220515_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_description',
            field=models.CharField(max_length=255),
        ),
    ]
